### PR TITLE
feat: yaml config & config generation on first run

### PR DESCRIPTION
**Pull request by masamerc**
## Overview
The primary purpose of this pull request is to incorporate YAML based configuration for the application, which previously used JSON based configuration. The newly added configuration.py is designed to handle creation, reading, and parsing of configuration using YAML instead of JSON. Additionally, this change removes the redundant 'config_reader.py' file and integrates its functionality into 'config.py'. Lastly, a dependency on the PyYAML library is added to facilitate the YAML operations, and the tests have been updated to reflect the new changes.

### New File: `goc/config.py`
- Implements the necessary functionality for handling YAML based configurations for the application. This includes functions for creation, reading and parsing configuration.
- Includes a default template for the commit and diff documentation. When the config file is created, these templates are written to it.
- An Enum class `TemplateType` is introduced for better readability.

### Deleted File: `goc/config_reader.py`
- This file used to handle configuration parsing related tasks for the application. This file was removed, and its functionality was integrated into 'config.py'.

### Modified File: `goc/goc.py`
- Made import changes to switch from the removed 'config_reader.py' to the newly implemented 'config.py'.

### Modified File: `poetry.lock`
- This file is modified to reflect the newly added PyYAML dependency.

### Modified File: `pyproject.toml`
- Added a dependence on the 'pyyaml' library.

### Modified File: `tests/test_goc.py`
- Tests are updated to reflect changes in 'config.py'. Specifically altered the test cases to fit the new YAML configuration routine.

### In `goc/config.py`
- YAML configuration implementation was added, with a default template configuration for diff and commit documentation. Functionality for reading and parsing this configuration was also added.

### In `goc/goc.py`
- Updated import statements to remove the deprecated 'config_reader.py' and replace with 'config.py'.

### In `poetry.lock` and `pyproject.toml`
- Added a dependency on the PyYAML library.

### In `tests/test_goc.py`
- Made changes in the test cases to reflect the new changes in 'config.py'. Modified the test cases to fit the updated configuration

### CODE REVIEW

**Comment by masamerc** [comment]
Related issue: https://github.com/djentleman/goc/issues/12

**Comment by masamerc** [comment]
@djentleman 
Feel free to test and let me know if anything doesn't work as intended

**Comment by masamerc** [comment]
I've renamed the file `config_reader` to `config` because now it doesn't just read. The diff shows the original has been deleted but I actually just changed some parts of it.

**Comment by masamerc** [comment]
*`goc diff` worked perfectly for this PR descritiption

**Review by djentleman — APPROVED** [review]

**Comment by djentleman** [comment]
looks good
i will do some testing on my side before releasing 0.6.1

next i will incorporate the default chat GPT version into the config file

**Comment by masamerc** [comment]
sounds good.

**Pull request merged**
